### ISSUE TITLE
Django version error

### ISSUE THREAD

**Issue by AlexErk** [ebu/radiodns-manager#128]
during:
docker-compose -f docker-compose-standalone-demo.yml up --build -d

got the error:
Collecting Django==2.1.6 (from lightweight-plugIt-proxy==1.0.0)
  Could not find a version that satisfies the requirement Django==2.1.6 

I changed the version to 2.1.7 in:

radiodns-manager/LightweightPlugitProxy/setup.py

And the install run fine.

However the : "admin" and "1234"  login on : http://localhost:4000

Lead to a 403 Error  "You don't have rights to view this page. Internal reason. only_orga_member_user"

**Comment by ioannisNoukakis** [comment]
Hi, thank you for your feedback. For some reason, the version 2.1.6 of Django does no longer exist on PyPI. Problem fixed in #129.

Cheers!
