### ISSUE TITLE
Create Service Provider Model

### ISSUE THREAD

**Issue by mhabegger** [ebu/radiodns-manager#45]
Create Service Provider Model for EBU codops attached to organisations
- Multiple Orga can have the same codops
- Aggregate all similar codops

Fields
- Name
- Description
- Weblink
- Location / Country-Point-Polygon
- Logos (various size see spec.)
- Service >> Channels/Stations
- DNS Service Provider, can be EBU but also external, if EBU generate downstream components

**Comment by mhabegger** [comment]
Implemented partially.
Missing features are:

- Location /Point-Polygon

**Comment by magicbadger** [comment]
Closing after opening separate issues to complete the geolocation work in the various objects (Service Provider, Station, Channel).
