### ISSUE TITLE
Add new channel enhancement

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-manager#56]
When adding a new channel for a station,

It would be nice to have the country of the organisation selected by default for the ECC list.
When adding lots of channels, it can be useful to avoid selecting each time the country.

Another nice to have would be to have a proposal for the PI based on the previous entry. Usually a PI code is the same for a given stations (even if it can sometimes happen to have different PI codes for the same stations)

**Comment by mhabegger** [comment]
Default Country base on the service provider will work in the next release.
About the PI and other codes. This is difficult to implement due to the various types of channels and should it pick up the last entry created or the last modified ?
We will keep this issue open although.

**Comment by magicbadger** [comment]
Closing in favour of new issues relating to PI and SId code suggestions for FM and DAB/DAB+ respectively.
