### ISSUE TITLE
Channel delete using tickbox

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-manager#69]
It happens that many channel must be deleted at the same time.
Instead of having individual delete buttons, it may be more easy to have a tickbox for each channel and then a delete button that would deleted ticked entries.

**Comment by coinchon** [comment]
same for "turn on" , "turn off" functionalities in service following

**Comment by mhabegger** [comment]
Feature added to change radiovis image on channels. Will keep ticket open for other sections in manager.

**Comment by magicbadger** [comment]
Closing in favour of a more specific issue.
