### ISSUE TITLE
Limit list size

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-manager#71]
Limit size of lists for My Channels, RadioVIS channels,.... when list are too long, this becomes sometimes extremely slow to display and edit (server or/navigator navigator side problem)

**Comment by mhabegger** [comment]
New way to handle channels and vis etc. Please test latest release.

**Comment by coinchon** [comment]
It works but is still very slow when the list is long, check channel inthe case of filtered list takes as much time as with the full list.

**Comment by mhabegger** [comment]
Filtering is just a display filter. In the background we still process the complete list.
We will change the check behaviour to be fired only on channels that are currently displayed by the filter.




On Jun 10, 2015, at 13:59, coinchon <notifications@github.com<mailto:notifications@github.com>> wrote:


It works but is still very slow when the list is long, check channel inthe case of filtered list takes as much time as with the full list.

-
