### ISSUE TITLE
add cost and offset to channel elements

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-manager#77]
Add cost and offset for channels (bearer).

Cost can be put as default to 100 for streaming, 50 for FM, and 20 for DAB as this is the usual order of priority for channels (broadcast preffered over streaming).

Offset should also be added, it is optional but can help the receiver to align broadcast channels and streaming when switching from one to the other.

See section 5.11.1 of ETSI TS 102 818 for more details.

**Comment by mhabegger** [comment]
@coinchon This is implemented. Please test and close.

**Comment by mhabegger** [comment]
Offset of Stream is put by default to 2000.

**Comment by coinchon** [comment]
When adding an IP channel (in my Channel), I don't see the cost and offset field but it seems the XML has it.
Offset should be in the form as a field (but can put 2000 by default) as delay offset may vary from a broadcaster to another, same for cost (cost should be put to higher value for streaming by default, for example 100, 50 for FM and 20 for DAB).

**Comment by mhabegger** [comment]
Add Offset and Cost for all channels instead of ServiceFollowing Entries
Add Flag for Serice Following into Channels and remove Service Following as separate table
