### ISSUE TITLE
MIME type for DAB/DAB+

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-manager#82]
According to the SI specification:
5.11.2 Digital Audio Broadcasting (DAB/DAB+)
The mimeValue attribute is required and shall be defined as audio/mpeg for DAB and audio/aacp for DAB+ services.

At the moment, the platform defaults to audio/mpeg when adding a DAB channel and one must edit manually each channel after creation in Service Following section (this can be long and complicated).
It would be beneficial to either select the kind of DAB channel when creating the entry (DAB or DAB+) or add DAB+ in the list of type of channel with the same settings as for DAB but with a different MIME Type.

**Comment by mhabegger** [comment]
Add mimetype field to channel form
